# Example: How to use the golang-builder action in your project

name: Build & Push Production Docker Image

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build, Test, and Deploy
        uses: cfindlayisme/golang-builder@v1  # Or use a local path for testing: ./path/to/golang-builder
        with:
          # Vault Configuration
          vault-addr: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          
          # GitHub Configuration
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          
          # Deployment Configuration
          deployment-name: 'wmb'
          staging-enabled: 'false'  # Set to 'true' to enable staging
          production-enabled: 'true'
